### ISSUE TITLE
systemd interaction

### ISSUE THREAD

**Issue by djh42** [StuartIanNaylor/log2zram#2]
I asked some questions related to log2ram on the systemd-devel mailing list that may be relevant for this fork. The thread starts at https://lists.freedesktop.org/archives/systemd-devel/2019-March/042312.html and there are two main suggestions:

(1) I was asking about how to allow journald to continue logging to the SD card. journald is intelligent about reducing writes but will try its best to write emergency messages during a crash, so these want to be written directly to persistent store, not buffered by log2*ram. The suggestion by Colin Guthrie is to use a bind mount. This would be a nice feature to add.

(2) I mentioned the Before=systemd-journald.service dependency and Leonard Poettering advised that it is better to use Before=systemd-journal-flush.service

I also notice the Before=apache2.service dependency and have a question about it. Why is it there? Is it just one example of a service that must not be started until the RAM log directories are prepared? What about other services that write logs, such as redis or mysql? Does the service file need customising on every machine where it is run or is there some other technique could be used?

**Comment by StuartIanNaylor** [comment]
Dunno I copied from log2ram and have been wondering the same as the more init directives you have the greater the chance of unnecessary spaghetti.
Just never got round to deleting and seeing, put up a branch and let us have a look.
Certain applications will fail if log files are not avail on start... I think is the rationale

I only started because it seemed a logical choice to minimise mem usage and use zram rather than tmpfs.
Got side tracked with how bad the ubuntu zram-config-0.5 is in entirety and how it doesn't check for previous zram usage.

Liking what pb66 https://github.com/azlux/log2ram/issues/65 is saying about olddir on different devices.

If you look at https://github.com/StuartIanNaylor/zramdrive its actually just a minimalist log2ram that if you set the dirs to /var/log its the same and doesn't have the directives apart from other zram services.

I have had quite a few questions to why certain things are included in log2ram hence the branches so all can see comment hack or copy.
I don't think log2ram should be called log2ram as much as I don't think the Ubuntu package should be called zram-conf whilst it only does swaps.
I am thinking log2ram, zramdrive & zram-swap-config can all be combined via a single ztab.conf that is just like a fstab or mtab file.
There really is no difference log2ram & zramdrive  apart from logrotate directives singular global ones and what pb66 is saying is great as it massively simplifies things whilst providing huge advantages.
My thoughts are that a working and good implementation of zram-config should be available and its called config because it allows you to config zram easily into many options.
You may have several swaps, zramdrives and a log2ram all on individual lines in a ztab.conf as there is very little difference and most of the sub routines are identical.

So yeah fire up a branch :) as like pb66 says about `renamecopy` some really good ideas seem to be being suggested.

**Comment by StuartIanNaylor** [comment]
https://github.com/StuartIanNaylor/zram-config the all-in-one with the suggestions.

Keep em rolling its a first draft but seems to be OK.
Current ztab is not what will be the default but just lets you check on install.

**Comment by StuartIanNaylor** [comment]
Yeah its a problem as Before=systemd-journal-flush.service means we start really early in the boot order. Unfortunately that means we are really late in the shutdown as its just the reverse of boot.
Pretty sure we are missing shutdown routines as they fail to access services already shutdown before them.

**Comment by StuartIanNaylor** [comment]
2 ways to go really guess I could create an early startup and late shutdown service.
Also doing a LSOF /var/log shows that it is systemd retaining open files.
```
removeZlog () {
	if [ ! -z "$OLDLOG_DIR" ]
	then
		cp -arvf /usr/local/share/zram-config/logrotate.conf.bak /etc/logrotate.conf 
	fi
	syncToDisk
	sync
	ZRAM_DEV=$(df "$ZRAM_DIR" | tail -1 | awk '{ print $1 }')
	DEV_NUM=$(echo "$ZRAM_DEV" | tr -dc '0-9')
	if [ ! -z "$ZRAM_DIR" ]
	then
		invoke-rc.d rsyslog stop
		umount $ZRAM_DIR/
	else
		return 1
	fi
	if [ ! -z "$BIND_DIR" ]
	then
		umount $BIND_DIR/
		rm -rf $BIND_DIR
		invoke-rc.d rsyslog start
		journalctl --flush
	else
		return 1
	fi
	echo "$DEV_NUM" > /sys/class/zram-control/hot_remove
	echo "$ZRAM_DEV removed" >&1 
}
```

```
createZlog () {
	invoke-rc.d rsyslog stop
	createZdir
	invoke-rc.d rsyslog start
	journalctl --flush
	if [ ! -z "$OLDLOG_DIR" ]
	then
		cp -arvf /etc/logrotate.conf /usr/local/share/zram-config/logrotate.conf.bak
		sed -i "/^weekly.*/i olddir $OLDLOG_DIR" /etc/logrotate.conf
		sed -i "/^weekly.*/i createolddir 755 root root" /etc/logrotate.conf
		sed -i "/^weekly.*/i renamecopy" /etc/logrotate.conf
	else
		echo "createZlog no oldlog dir in ztab"
	fi
}
```
I am reading  https://lists.freedesktop.org/archives/systemd-devel/2019-March/042312.html but wondering why start so early and would not a start / stop on rsyslogd and `journalctl --flush' on zram /var/log creation and deletion do the job?

**Comment by StuartIanNaylor** [comment]
djh42 would you have a look at https://github.com/StuartIanNaylor/zram-config

**Comment by djh42** [comment]
> djh42 would you have a look at https://github.com/StuartIanNaylor/zram-config

Hi Stuart. I'm not really sure what I'm looking at. I think it needs to start as soon as /var becomes available and before any service tries to write to it, does it not? Similarly, it needs to shut down as late as possible, after all other services have stopped so it can copy their logs to persistent storage and shut down just before /var disappears?

**Comment by StuartIanNaylor** [comment]
It can not start before /var is available as /var is part of the root directory.
Also it can not shut down so late that mounts and services are no longer available.
Not sure why it should have to.

Just mount zramlog and restart rsyslog same with umount.
